kind: Secret
apiVersion: v1
metadata:
  name: whoami-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/mydemosecret"
type: Opaque
stringData:
  sample-secret: <app_password>
  sample-token: <app_token>